In [2]:
# Data Analytics  - Python
# Programming Language
# program

SyntaxError: invalid syntax (344185551.py, line 2)

In [1]:
a1="True"
b2=78
print("Hello classa",",",a1)
print(a1)
print(b2)
print(type(a1))

Hello classa , True
True
78
<class 'str'>


In [ ]:
# Interpreter ,compiler based
# Data Type
# int,float,bool,string
print(type(5>7))

In [2]:
# Methematical Operatot:+,-,*,/,%.//,**
a=12
b=2
print("The sum is ",a+b)
print("The difference is ",a-b)
print("The Product is ",a*b)
print("The division is ",a/b)
print("The remainder is ",a%b)
print("The floor division is ",a//b)
print("The exponent is ",a**b)

The sum is  14
The difference is  10
The Product is  24
The division is  6.0
The remainder is  0
The floor division is  6
The exponent is  144


In [3]:
Bhumika=90
a="Bhumika"
# print(a)
a="Prime Minister"
# print(a)
a=True
e=35
a=chr(e)
a=9.75
print(a)
print(type(a))

9.75
<class 'float'>


In [4]:
a=95
b=a
print(b)

95


In [6]:
ord('A')

65

In [ ]:
a="Shubham"
b="hero"
c=9
print(a+b)
print(c+a)

In [9]:
a=int(input("Enter something"))
print(a)
print(type(a))

Enter something 45


45
<class 'int'>


In [ ]:
a=int("65")
print(type(a))

In [ ]:
# rule to declare the name of Variable
a_b="Shubham"
print(a_b)

In [ ]:
# area of circle
radius=float(input("Enter the radius :"))
area=3.14*radius*radius
print("The area of circle is :",area)

In [ ]:
3.14*7.8*7.8


In [ ]:
l=float(input("Enter the length :"))
b=float(input("Enter the bredth :"))

parameter=2*(l+b)
print("The parameter of rectanle is :",parameter)

In [ ]:
# * * * * *
#  * * * *
# * * * * *
#  * * * *
# * * * * *
# for i in range(0,5):
#     for j in range(0,5):
#         if i%2==0:
#             print("*",end="")
#             print(" ",end="")
#         else:
#             # pass
#             print(" ",end="")
#             if j==4:
#                 print(" ",end="")
#                 break
#             print("*",end="")
#     print()

In [ ]:
# *
# **
# ***
# ****
# ***
# **
# *
# for i in range(1,6):
#     print("*"*i)
# for j in range(4,0,-1):
#     print("*"*j)

In [ ]:
# n=9
# a=9
# for i in range(n):
#     for j in range(6):
#         if i<5: 
#             if i+1==j:
#                 break
#             print("*",end="")  
#     else:
#         for k in range
#     print(",")

In [ ]:
# n=23
# a=24
# for i in range(1,n+1):
#     if i<=n/2:
#         for j in range(i):
#             print("*",end="")  
#     else:
#         for j in range(a-i):
#             print("*",end="")  
#     print("")

In [ ]:
 #  ***                                                                   
 # *   *                                                                  
 # *   *                                                                  
 # *****                                                                  
 # *   *                                                                  
 # *   *                                                                  
 # *   *
# for i in range(0,7):
#     for j in range(0,5):
#         if (i==0 and j==0) or (i==0 and j==4):
#             print(" ",end="")
#         else:
#             if (j==0 or j==4 or i==0):
#                 print("*",end="")
#             else:
#                 if i==3:
#                     print("*",end="")
#                 else:
#                     print(" ",end="")
#     print()

In [ ]:
p=float(input("Enter the Principle amount :"))
r=float(input("Enter the rate:"))
t=float(input("Enter the time(in Years):"))
si=(p*r*t)/100
print("The simple interest will be ",si)

In [ ]:
a=90
b=45
c=a
a=b
b=c
print(a)
print(c)

In [ ]:
a=90
b=45
a=a+b    #a=90+45=135
b=a-b    #b=135-45=90
a=a-b    #a=135-90=45
print(a)
print(b)

In [ ]:
a=float(input("Enter the a :"))
b=float(input("Enter the b :"))
c=float(input("Enter the c :"))
root1=((-b)+(((b**2)-(4*a*c))**0.5))/(2*a)
root2=((-b)-(((b**2)-(4*a*c))**0.5))/(2*a)
print(root1,root2)

In [ ]:
# comparison Opeartor
# >,<,>=,<=,==,!=
# print(4!=5)
# conditional Statement
a=5
if a>10:  #False
    print("Hello")
else:
    print("bye")

In [ ]:
a=int(input("ENter any number :"))
if a%2==0:
    print(a," is even")
else:
    print(a," is not even")

In [ ]:
a=int(input("ENter any number :"))
if a%2==1:
    print(a," is odd")
else:
    print(a," is not odd")

In [ ]:
a=int(input("ENter any number :"))
if a>0:
    print(a," is positive")
elif a==0:
    print(a," is zero")
else:
    print(a," is negative")

In [ ]:
a=int(input("ENter any number :"))
if a%2==0:
    if a%4==0:
        print(a ," is even and also divisible by 4")
    else:
        print(a ," is even but not divisible by 4")
else:
    if a%3==0:
        print(a ," is odd and also divisible by 3")
    else:
        print(a ," is odd but not divisible by 3")

In [ ]:
# logical Operator 
# and , or , not
a=int(input("ENter any number :"))
if a%2==0 and a%4==0:
    print(a ," is even and also divisible by 4")
elif a%2==0:
    print(a ," is even but not divisible by 4")
elif a%2==1 and a%3==0:
    print(a ," is odd and also divisible by 3")
else:
    print(a ," is odd but not divisible by 3")

In [ ]:
# 2000  -no discount
# 2000-5000 10% discount
# 5000-10000 15% discount
# 10000<      20%discount
purchase_amount=int(input("Enter the purchase amount :"))
payble_amount=0
discount=0
if purchase_amount<=2000:
    payble_amount=purchase_amount
    print("You will get no discount and you have to pay :",payble_amount)
elif purchase_amount>2000 and purchase_amount<=5000:
    discount=purchase_amount*0.1
    payble_amount=purchase_amount-discount
    print("You will get 10% discount and you have to pay :",payble_amount)
elif purchase_amount>5000 and purchase_amount<=10000:
    discount=purchase_amount*0.15
    payble_amount=purchase_amount-discount
    print("You will get 15% discount and you have to pay :",payble_amount)
else:
    discount=purchase_amount*0.2
    payble_amount=purchase_amount-discount
    print("You will get 20% discount and you have to pay :",payble_amount)

In [ ]:
# datatype,variable, mathemetical Operator
# comparison Operator, logical Operator
# int, string, float,bool,list, tuple, set ,dictionary,numpy
# a=88
# print
# print(78+87)
hindi=95
english=90
print(hindi)
print(hindi+math)

In [ ]:
# Python interpreter based 
# compiler ,interpreter
a
b=98
print(a+b)

In [ ]:
c='shruti'
d=True
print(type(d))
# print(c+d)

In [ ]:
input
process
output

In [ ]:
a=891
b=123
c=a+b
d=a-b
e=a*b
f=a/b
h=a%b
i=a//b
j=a**b
print(c)
print(d)
print(e)
print(f)
print(h)
print(i)
print(j)

In [ ]:
print(4**3)

In [ ]:
a="shruti"
b=4
# print(a+b)
# print(a-b)
print(a*b)
# print(a/b)

In [ ]:
print(type(90>56))

In [ ]:
>,<,>=,<=,==,!=

In [ ]:
a=78
a!=6


In [ ]:
#WAP to calculate simple interest
p=int(input("Enter the principle amount :"))
r=int(input("Enter the rate :"))
t=int(input("Enter the timeperiod(in years) :"))
si=(p*r*t)/100
print("The simple interest will be :",si)

In [ ]:
a=int('45')
b=90
print(a+b)

In [ ]:
Rate=98
print(Rate)

In [ ]:
#WAP to find the area of triangle if 3 sides are given
# area=underoot s(s-a)(s-b)(s-c)
a=int(input("Enter the first side :"))
b=int(input("Enter the second side :"))
c=int(input("Enter the third side :"))
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print("The area of triangle is :",area)

In [ ]:
length=int(input("Enter the length :"))
width=int(input("Enter the width :"))
parameter=2*(length + width)
print("The parameter is :",parameter)

In [ ]:
a=int(input("ENter any number "))
b=int(input("ENter any number "))
c=int(input("ENter any number "))
root1= ((-b)+(((b**2)-(4*a*c)))**0.5)/(2*a)
root2= ((-b)-(((b**2)-(4*a*c)))**0.5)/(2*a)
print(root1 ,"    ",root2)

In [ ]:
length=80
width=100
wot=2
areaoffield=length*width
areaoffieldwithtrack=(length+4)*(width+4)
print("The are of track is :",areaoffieldwithtrack-areaoffield)

In [ ]:
# logical Operator
# and, or, not

In [ ]:
# condition statement--
# if condition:
#     program
# else:
#     program
a=int(input("Enter any number :"))
if a<0:  #true  -85<0
    print("The number is negative")
else:
    print("The number is positive")
    

In [ ]:
age=int(input("Enter the age "))
if age>=18 or age<=30:
    print("You are eligible for examination")
else:
    print("Not Eligible")

In [ ]:
# no_of_days
# age
# wages :
# 18-30   900rupees per day
# 30-40   1000 rupeesper day

In [ ]:
age=int(input("ENter the age :"))
wages=0
if age>=18 and age<=30:
    no_of_days=int(input("ENter the number of days :"))
    wages=no_of_days*900
    print("The wages will be according to your age :",wages)
elif age>30 and age<=40:
    no_of_days=int(input("ENter the number of days :"))
    wages=no_of_days*1000
    print("The wages will be according to your age :",wages)
else:
    print("You are not eligile to work in my company")

In [ ]:
# 2000   -no discount
# 2000-5000   10% discount
# 5000 10000   15% discount
# 10000<        20% discount
purchased_amount=int(input("Enter the purchased amount :"))
payble_amount=0
discount=0
if purchased_amount>0 and purchased_amount<=2000:
    payble_amount=purchased_amount
    print("You will get no discount and you have to pay :",payble_amount)
    
elif purchased_amount>2000 and purchased_amount<=5000:
    discount=purchased_amount*0.1
    payble_amount=purchased_amount-discount
    print("You will get 10 % discount and you have to pay :",payble_amount)
    
elif purchased_amount>5000 and purchased_amount<=10000:
    discount=purchased_amount*0.15
    payble_amount=purchased_amount-discount
    print("You will get 15 % discount and you have to pay :",payble_amount)
    
elif purchased_amount>10000:
    discount=purchased_amount*0.2
    payble_amount=purchased_amount-discount
    print("You will get 20 % discount and you have to pay :",payble_amount)
else:
    print("Please enter positive number ")

In [ ]:
a=76567
print(a%10)

In [ ]:
a=int(input("ENter any number :"))
last_digit=a%10
print(last_digit)
if last_digit%3==0:
    print("The last digit of the number is divisible by 3")
else:
    print("The last digit of the number is not divisible by 3")

In [ ]:
month=int(input("Enter the number of month :"))
if month==1:
    print("THe month will be January and the number of day in this month 31")
elif month==2:
    print("THe month will be February and the number of day in this month ",28/29)
else:
    print("Give input between 1 to 12")

In [ ]:
# no_of_days
# age
# wages :
# 18-30       m 900rupees per day
#             f 950rupees per day
# 30-40     m1000 rupeesper day
#           f 1100 rupeesper day

In [ ]:
age=int(input("ENter the age :"))

if age>=18 and age<=30:
    no_of_days=int(input("ENter the number of days :"))
    gender=input("ENter the gender (M/F) :")
    if gender=='M':
        wages=no_of_days*900
        print("The wages will be according to your age and gender :",wages)
    elif gender=='F':
        wages=no_of_days*950
        print("The wages will be according to your age and gender :",wages)
    else:
        print("Give correct input (M or F")
elif age>30 and age<=40:
    no_of_days=int(input("ENter the number of days :"))
    gender=input("ENter the gender (M/F) :")
    if gender=='M':
        wages=no_of_days*1000
        print("The wages will be according to your age and gender :",wages)
    elif gender=='F':
        wages=no_of_days*1100
        print("The wages will be according to your age and gender :",wages)
    else:
        print("Give correct input (M or F")
else:
    print("You are not eligile to work in my company")

In [ ]:
print('A'=='a')

In [ ]:
a=ord('a')
print(a)

In [ ]:
year=int(input("Enter the year : "))
if (year%4==0 and year%100!=0) or (year%400==0):
    print("leap year")
else:
    print("no")

In [ ]:
year=int(input("Enter the year : "))
if (year%4==0 and year%100!=0):
    print("leap year")
elif year%400==0:
    print("leap year")
else:
    print("no")

In [ ]:
# unit
# 100>    0
# 100-200    5
# 200        10
unit=int(input("ENter the unit :"))
bill=0
if unit<=100:
    bill=0
    print("ENjoy , You dont have pay anything")
elif unit>100 and unit<=200:
    bill=(unit-100)*5
    print("You have to pay the bill :",bill)
else:
    bill=((unit-200)*10)+500
    print("You haveto pay the bill :",bill)

In [ ]:
# a=['red', 'pink', 'green', 'white', 'black']
# b=['white', 'orange', 'pink', 'black']
# # b=['red', 'green', 'black', 'orange']
# # b=['red', 'pink', 'green', 'white', 'black']
# # b=['red', 'pink', 'green', 'white', 'black']
# count=0
# for i in range(len(a)):
#     for j in range(len(b)):
#         if a[i]==b[j]:
            
#             if i<=j:
#                 count=count+1
#             else:
#                 break
# notice=0
# for i in a:
#     if i in b:
#         notice+=1
# if count==notice:
#     print("Orderd")
# else:
#     print('not')

In [ ]:
# a=[1,1,1,1,1,1,1,1,1,1,1,1,1,'red', 'green', 'black', 'orange']
# # b=['red', 'pink', 'green', 'white', 'black']
# b=['white', 'orange', 'pink', 'black']
# cc=0
# for i in a:
#     for j in b:
#         if i==j:
#             # print(i)
#             cc+=1
#             break
#     if cc==1:
#         break
# re=a.index(i)
# print(re)
# count=0
# for i in range(re,len(a)):
#     for j in range(len(b)):
#         if a[i]==b[j]:
#             if i<=j+re:
#                 count=count+1
#             else:
#                 break
# notice=0
# for i in a:
#     if i in b:
#         notice+=1
# if count==notice:
#     print("Orderd")
# else:
#     print('not')

In [ ]:
# a=[3, 40, 41]*6

# count=0
# for i in range(len(a)):
#     count+=1
#     print(a[i],end="")
#     if count==3:
#         count=0
#         print()
        
        


In [ ]:
# a=[3, 40, 41]
# import itertools
# b=itertools.combinations(a,3)
# print(b)

In [ ]:
# from itertools import combinations,permutations
# a=[3, 40, 41]
# li=[]
# for i in permutations(a, 3):
#     # print(i)
#     b=""
#     nu=""
#     for j in i:
#         b=(b+str(j))  
#     nu=b
#     li.append(int(nu))
# print(max(li))


In [ ]:
# my_list = [1, 2, 3, 4]
# for combo in combinations(my_list, 2):
#     print(combo)

In [ ]:
# itertools.permutations()

In [ ]:
# Why Python
# Syntax Easy
# Python Libraries available 

In [ ]:
# print("Hello Class")

In [ ]:
# a=90
# print(a)

In [ ]:
# int, string, float, char, bool
print("Class")

In [ ]:
interpreted based Language

In [ ]:
a=90
# print(a)
print(b)

In [ ]:
# Data Type
# int, string, float, char, bool
a=90.8
print(type(a))

In [ ]:
a=chr(65)
print(a)
print(type(a))

In [ ]:
a=float(90)
print(type(a))

In [ ]:
true=90
a=true
print(a)
print(type(a))

In [ ]:
b=87
a=b
print(a)
print(b)

In [ ]:
a,b,c=90,100,110
print(a)
print(b)
print(c)

In [ ]:
a=int(input("Enter the value of a :"))
print(type(a))

In [ ]:
# arithmatic Operator
#+,-,*,/,%,//,**
# print(8+9)
# print(14//3)
print(14**3)

In [ ]:
radius=float(input("Enter the radius of Sphere :"))
volume=(4/3)*3.14*(radius**3)
print("the volume of sphere is :",volume)

In [ ]:
a=87
b=90
# a=90
# b=87
a,b=b,a
print(a)
print(b)


In [ ]:
# Comparison Operator 
# >,<,>=,<=,==,!=
a=90
b=90
a!=b
# print(a)
# print(b)

In [ ]:
if condition:
    expression
elif condition:
    expression
else:
    expression

In [ ]:
#if number is divisible by 7 or not
a=int(input("Enter any number :"))
if a%7==0:
    print("the number is divisble by 7")
else:
    print("the number is not divisble by 7")

In [ ]:
#if number is divisible by 7 or 5  not
a=int(input("Enter any number :"))
if a%7==0:
    print("the number is divisble by 7")
elif a%5==0:
    print("the number is divisible by 5 ")
else:
    print("the number is not divisble by 7 and 5")

In [ ]:
# logical Operator
# and ,or, not
#if number is divisible by 7 and 5  not
a=int(input("Enter any number :"))
if a%7==0 or a%5==0:
    print("the number is divisble by 7 and 5")
else:
    print("the number is not divisble by 7 and 5")

In [ ]:
a=float(input("Enter first number :"))
b=float(input("Enter second number :"))
opt=input("Enter the operator :")
if opt=="+":
    print("The sum will be :",a+b)
elif opt=="-":
    print("The difference will be :",a-b)
elif opt=="*":
    print("The product will be :",a*b)
elif opt=="/":
    print("The divide will be :",a/b)
else:
    print("give correct operator(+,-,*,/)")

In [ ]:
# a,b,c
# a==b==c  equi
# a!=b!=c  scale
a=float(input("Enter first side :"))
b=float(input("Enter second side :"))
c=float(input("Enter third side :"))
if a==b==c:
    print("Equiletral")
elif a!=b!=c:
    print("Scalene")
else:
    print("Isoceles")


In [ ]:
a=float(input("Enter first side :"))
b=float(input("Enter second side :"))
c=float(input("Enter third side :"))
if a+b>c:   #2+3>100
    if b+c>a:
        if a+c>b:
            print("The triangle will be possible")
        else:
            print("The triangle will not be possible")
    else:
        print("The triangle will not be possible")
else:
    print("The triangle will not1 be possible")

In [ ]:
# for, while
a="Shivam"


In [ ]:
# membership Operator : in, not in
a="Shivzam"
if 'z' in a:
    print("Yes")

In [ ]:
for i in range(1,10):
    print(i,"Hello Class")

In [ ]:
for i in "Shivam":
    print(i)

In [ ]:
for i in range(5,10):
    print(i)

In [ ]:
# for i in range(len("Shivam")):
#     print(a[i])

In [ ]:
# for i in range(1,101):
#     if (i%2==0):
#         print(i)

In [ ]:
# for i in range(2,101,2):
#     print(i)

In [ ]:
sum=0
for i in range(1,11):
    sum=sum+i
print(sum)

In [ ]:
sume=0
sumo=0
for i in range(1,101):
    if i%2==0:
        sume=sume+i
    
    else:
        sumo=sumo+i
print("The sum of all even number is :",sume)
print("The sum of all odd number is :",sumo)

Write a Python program to convert a given heterogeneous list of scalars into a string.
Sample Output:
Original list:
['Red', 100, -50, 'green', 'w,3,r', 12.12, False]
Convert the heterogeneous list of scalars into a string:
Red,100,-50,green,w,3,r,12.12,False

In [ ]:
# a=['Red', 100, -50, 'green', 'w,3,r', 12.12, False]
# for i in a:
#     print(i,end=",")

In [ ]:
# a=['Red', 100, -50, 'green', 'w,3,r', 12.12, False]
# b=",".join(str(i) for i in a)
# print(type(b))
# print(b)
# print(i)

In [ ]:
# my_list = ['apple', 'banana', 'cherry']
# comma_separated_string = ','.join(my_list)
# print(comma_separated_string)

In [ ]:
# Write a Python program to sum two or more lists. The lengths of the lists may be different.
# Original list:
# [[1, 2, 4], [2, 4, 4], [1, 2]]
# Sum said lists with different lengths:
# [4, 8, 8]
# Original list:
# [[1], [2, 4, 4], [1, 2], [4]]
# Sum said lists with different lengths:
# [8, 6, 4]

In [ ]:
# a=[[1, 2, 4], [2, 4, 4], [1, 2]]
# sumlist=[]
# sum=0
# for i in range (len(a)):
#     for j in range(len(min(a))):
#         print(a[j][i])

In [ ]:
# print(min(a))

In [ ]:
# a=[[1, 2, 4], [2, 4, 4], [1, 2]]
# sumlist=[]
# a=sorted(a,key=len,reverse=True)
# # print(a)
# loop=len(a[0])
# for i in range(len(a)):
#     for j in range(loop):
#         if loop>len(a[i]):
#             a[i].append(0)
#     # print(a[i])
# # print(a)
# for i in range(len(a[i])):
#     sum=0
#     for j in range(len(a)):
#         sum=sum+a[j][i]
#     sumlist.append(sum)
# print(sumlist)

In [ ]:
# for , while
for i in range(1,11,2):
    print(i,"Hello Class")

In [ ]:
for i in range(10,1,-1):
    print(i)

In [ ]:
i=1
while i<=10:   #1<=10
    print(i)
    i=i+1

In [ ]:
i=10
while i>=1:
    print(i)
    i=i-1

In [ ]:
for i in range(2,20,2):
    print(i)

In [ ]:
for i in range(1,21):
    if i%2==0:
        print(i)

In [ ]:
i=1
while i<=20:
    if i%2==1:
        print(i)
    i=i+1

In [ ]:
for i in range(20,2,-2):
    print(i)

In [ ]:
i=20
while i>=1:
    if i%2==0:
        print(i)
    i=i-1

In [ ]:
i=21
while i>=1:
    if i%2==0:
        print(i)
    i=i-1

In [ ]:
i=19
while i>=1:
    print(i)
    i=i-2

In [ ]:
n=int(input("Enter any number :"))
for i in range(1,11):
    print(n,"X",i,"=",n*i)

In [ ]:
n=int(input("Enter any number :"))
i=1
while i<=10:
    print(n,"X",i,"=",n*i)
    i=i+1

In [ ]:
n=int(input("Enter any number"))   #672
rem=0
prod=1
while n!=0:
    rem=n%10
    prod=prod*rem
    n=n//10
print(prod)

In [ ]:
89//10

In [ ]:
# 5!
# 5*4*3*2*1
n=int(input("Enter any number")) 
fact=1
while n>=1:
    fact=fact*n
    # print(n)
    n=n-1
print("The factorial will be ",fact)

In [ ]:
n=int(input("Enter any number"))   #672
sum=0
while n!=0:
    rem=n%10
    sum=sum+rem
    n=n//10
print(sum)

In [ ]:
n=input("Enter any number")
sum=0
for i in n:
    sum=sum+int(i)
print(sum)

In [ ]:
# primeNumber
n=int(input("Enter any number"))
i=2
count=0
while i<n:   #2<5
    if n%i==0:
        count=count+1
    i=i+1
if count==0:
    print("Prime number ")
else:
    print("Not prime number ")

In [ ]:
for i in "Python":
    print(i,end=" ")

In [ ]:
x="123"
for i in x:
    print("a",i)

In [105]:
# break , continue , pass
i=1
while i<=10:
    if i==6:
        break
    print(i)
    i=i+1

1
2
3
4
5


In [107]:
i=1
while i<=10:
    if i==6:
        continue
    print(i)
    i=i+1

1
2
3
4
5


KeyboardInterrupt: 

In [112]:
for i in range(1,11):
    if i==6:
        continue
    print(i)

1
2
3
4
5
7
8
9
10


In [118]:
for  i in range(1,10):
    if i==6:
       pass 
    print(i)

1
2
3
4
5
6
7
8
9


In [2]:
i=10
while True:
    if i%3==0:
        break
    print("A")
    i=i-1

A


In [8]:
i=2
for x in range(i):
    i=i+1
    print(i)
    print(i)

3
3
4
4


In [14]:
i=2
for x in range(i):
    x+=1
    print(x)
print(x)

1
2
2


In [28]:
for i in range(1,6):
    for j in range(1,i):
        print(j,end=" ")
    print()


1 
1 2 
1 2 3 
1 2 3 4 


In [10]:
a=int(input("ENter first number :"))
b=int(input("ENter second number :"))
if a<b:
    while a<=b:
        count=0
        for i in range(2,a):
            if a%i==0:
                count+=1
        if count==0:
            print(a)
        a=a+1
else:
    while b<=a:
        count=0
        for i in range(2,b):
            if b%i==0:
                count+=1
        if count==0:
            print(b)
        b=b+1

ENter first number : 26
ENter second number : 14


17
19
23


In [24]:
a=int(input("ENter any number :"))
b=a
rev=0
while a!=0:
    rem=a%10
    rev=rev*10+rem
    a=a//10
if b==rev:
    print("Palindrome ")

ENter any number : 12321


Palindrome 


In [28]:
x=int(input("ENter any number :"))
n=int(input("ENter any number :"))
i=1
sum=0
fact=1
while i<=n:
    fact=fact*i
    sum=sum+((x**i)/fact)
    i=i+1
print(sum+1)

ENter any number : 2
ENter any number : 2


5.0


In [34]:
a=65
for i in range(1,6):
    for j in range(i):
        print(chr(a),end=" ")
        a=a+1
    print()

A 
B C 
D E F 
G H I J 
K L M N O 


In [46]:
#     *
#    **
#   ***
#  ****
# *****

for i in range(1,6):
    for j in range(6-i):
        print(" ",end="")
    for j in range(i):
        print("*",end="")
    print()

     *
    **
   ***
  ****
 *****


In [58]:
#     *
#    ***
#   *****
#  *******
# *********
for i in range(1,6):
    for j in range(6-i):
        print(" ",end="")
    for j in range(2*i-1):
        print("*",end="")
    print()

     *
    ***
   *****
  *******
 *********


In [70]:
# *********
#  *******
#   *****
#    ***
#     *

for i in range(1,6):
    for j in range(i):
        print(" ",end="")
    for j in range(12-2*i-1):   #9,7,5,3,1
        print("*",end="")
    print()

 *********
  *******
   *****
    ***
     *


In [80]:
#     *
#    * *
#   *   *
#  *     *
# *********
for i in range(1,6):
    for j in range(6-i):
        print(" ",end="")
    for j in range(2*i-1):
        if j==0 or  j==2*i-2 or i==5:
            print("*",end="")
        else:
            print(" ",end="")
    print()

     *
    * *
   *   *
  *     *
 *********


In [101]:
#     *
#    * *
#   *   *
#  *     *
# *       *
#  *     *
#   *   *
#    * *
#     *


#  ****
# *    *
# *    *
# ******
# *    *
# *    *
#    **
#    * *
#   *   *
#  *     *
# *       *
#  *     *
#   *   *
#    * *
#     *
n=10
while n>5:
    for i in range(1,int(n/2)):
        for j in range(int(n/2)-i):
            print(" ",end="")
        for k in range(2*i-1):
            if k==0 or k==2*i-2:
                print("*",end="")
            else:
                print(" ",end="")
        print()
    break
    n=n-1
while n-5>=1:
    for i in range(2,int(n/2)):
        for j in range(i):
            print(" ",end="")
        for k in range(2*int(n/2)-2*i-1):
            if k==0 or k==2*int(n/2)-2*i-2:
                print("*",end="")
            else:
                print(" ",end="")  
        print()
    break
    n=n-1

    *
   * *
  *   *
 *     *
  *   *
   * *
    *


In [131]:
#  ****
# *    *
# *    *
# ******
# *    *
# *    *
n=6
for i in range(n):
    for j in range(n):
        if (i==0 and j==0) or (i==0 and j==5):
            print(" ",end="")
        elif i==0 and 1<=j<n:
            print("*",end="")
        else:
            if j==0 or j==n-1:
                print("*", end="")
            elif i==3:
                print("*",end="")
            else:
                print(" ",end="") 
    print()

 **** 
*    *
*    *
******
*    *
*    *


In [141]:
n=6
for i in range(n):
    for j in range(n):
        # print("*",end="")
        if (i==0 and j==0) or (i==0 and j==5):
            print(" ",end="")
        elif i==0 and 1<=j<n:
            print("*",end="")
        else:
            if j==0 or j==n-1:
                print("*", end="")
            elif i==3:
                print("*",end="")
            else:
                print(" ",end="") 
    print()

 **** 
*    *
*    *
******
*    *
*    *


In [183]:
# Sequential Data Type
# list, tuple, string
# collection
# Set
# Mapper
# Dictionary
# list
a=[1,2,3,0,"Sohan","Kartik","Ramu",True,8.90,[3,4,5],89]
print(type(a))
print(len(a))
# for i in a:
#     # print(i)
# print(type(a[9]))
# print(a[9][2])
# print(a[-11])
print(a[2:9:2])

<class 'list'>
11
[3, 'Sohan', 'Ramu', 8.9]


In [191]:
a=[1,2,3,4,5,6,7,78,21,-11,120,145]
# for i in a:
#     if i%2==0:
#         print(i)
for i in range(len(a)):
    if a[i]%2==0:
        print(a[i])

2
4
6
78
120


In [67]:
a=[1,2,7,3,4,2,5,6,7]
# print(type(a))
# a.append(78)
# a.clear()
# del a
# b=a.copy()
# a.count(7)
b=["h","hero",90]
# a.append(b)
# a.extend(b)
# for i in range(len(a)):
#     if a[i]==7:
#         print(i)
# a.insert(3,"Prateek")
# a.pop(2)
# a.remove(2)
# for i in range(len(a)):
#     if a[i]==7:
#         a.remove(a[i])
# a.reverse()
# a.sort(reverse=True)
# print(a)
# print(max(a))

[7, 7, 6, 5, 4, 3, 2, 2, 1]
7


In [ ]:
a=[1,2,3]
b=[4,5,6]
output1=[1,2,3,4,5,6]
outpu2t=[1,4,2,5,3,6]

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8]
ouput=[1,6,2,7,3,8,4,5]

In [ ]:
a=[1,2,3]
b=[4,5,6,7,8]
ouput=[1,4,2,5,3,6,7,8]

In [71]:
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [73]:
a=[1,2,3]
b=[4,5,6]
# c=[1,4,2,5,3,6]
c=[]
for i in range(len(a)):
    c.append(a[i])
    c.append(b[i])
print(c)

[1, 4, 2, 5, 3, 6]


In [83]:
a=[1,2,3,4,5]
b=[6,7,8]
# c=[1,6,2,7,3,8,4,5]
c=[]
for i in range(len(a)):
    c.append(a[i])
    if i<len(b):
        c.append(b[i])
print(c)

[1, 6, 2, 7, 3, 8, 4, 5]


In [89]:
a=[1,2,3]
b=[4,5,6,7,8]
# ouput=[1,4,2,5,3,6,7,8]
c=[]
for i in range(len(b)):
    if i<len(a):
        c.append(a[i])
    c.append(b[i])
print(c)

[1, 4, 2, 5, 3, 6, 7, 8]


In [91]:
a=[-1,-2,-7,-3,-4,-2,-5,-6,-7]
for i in a:
    if i==7:
        a.remove(i)
print(a)

[1, 2, 3, 4, 2, 5, 6]


In [93]:
a=[44,-1,-2,-7,-3,-4,-2,55,-5,-6,-7]
max=a[0]
for i in range(len(a)):
    if max<a[i]:
        max=a[i]
print(max)

55


In [95]:
a=[44,-1,-2,-7,-3,-4,-2,55,-5,-6,-7]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i]>a[j]:
            a[i],a[j]=a[j],a[i]
print(a)

[-7, -7, -6, -5, -4, -3, -2, -2, -1, 44, 55]


In [7]:
a=[44,-1,-2,-7,-3,-4,-2,55,-5,-6,-7]
c=max(a)
b=[]
b.append(c)
print(b)
for i in range(len(a)):
    if a[i]<b[i]:
        b.append(a[i])
print(b)

[55]


IndexError: list index out of range

In [15]:
a=[44,-1,-2,-7,-3,-4,-2,55,-5,-6]
for i in range(1,int(len(a)/2)+1):
    a[i-1],a[-i]=a[-i],a[i-1]
print(a)

[-6, -5, 55, -2, -4, -3, -7, -2, -1, 44]


In [13]:
a=9
b=8
a,b=b,a
print(a)
print(b)

8
9


In [31]:
a=(2,4,6,7,4)
print(type(a))
print(a)
a[1]=44
print(a)

<class 'tuple'>
(2, 4, 6, 7, 4)


TypeError: 'tuple' object does not support item assignment

In [33]:
a=(2,4,6,7,4)
b=list(a)
b[2]=87654
a=tuple(b)
print(a)

(2, 4, 87654, 7, 4)


In [37]:
# 3X3
# [[],[],[]]
rows=int(input("Enter any number :"))
columns=int(input("Enter any number :"))
a=[]
for  i in range(rows):
    b=[]
    for j in range(columns):
        user=int(input("Enter anything"))
        b.append(user)
    a.append(b)
print(a)
        

Enter anything 1
Enter anything 2
Enter anything 3
Enter anything 4
Enter anything 5
Enter anything 6
Enter anything 7
Enter anything 8
Enter anything 9


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [43]:
# 123
# 456
# 789
print(a)
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j],end="")
    print()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
123
456
789


In [87]:
# Set
a={1,2,3,3,4,5,5,65,"String"}
b={1,2,3,88}
# print(type(a))
# a.add(78)
# a.clear()
# a.difference_update(b)
# a.discard(True)
# a.remove(1)
a.update(b)
print(a)



{1, 2, 3, 4, 5, 65, 88, 'String'}


In [93]:
# a={1,2,3}
# b={4,5,6}
# c={7,8,9}
# d=set()
# d={1,2,3,4,5,6,7,8,9}
[print(x) for x in [1,2,3]]
for x in [1,2,3] print(x)

SyntaxError: invalid syntax (723711512.py, line 7)

In [95]:
a=[1,2,3]
a=[x+5 for x in a]
print(a)

[6, 7, 8]


In [31]:
a={1,2,3,3,4,5,5,65,"String"}
b={1}
# a.symmetric_difference(b)
# a.symmetric_difference_update(b)
print(a)

{1, 2, 3, 4, 5, 65, 'String'}


In [35]:
# a.isdisjoint(b)
b.issubset(a)

True

In [41]:
a.issuperset(b)

True

In [43]:
a=frozenset({1,2,3,4,4})

In [ ]:
list=['Red','Green','White','Black','Pink']
# remove 0th,4th and 5th element from the list
for i in [5, 4, 0]:
    del list[i]
print(list)

In [77]:
list1=['Red','Green','White','Black','Pink','green']
rm_index=[0,4,3]
rm_item=[]
for i in range(len(list1)):
    if i in rm_index:
        rm_item.append(list1[i])
print(rm_item)
for i in list1:
    if i in rm_item:
        list1.remove(i)
print(list1)

['Red', 'Black', 'Pink']
['Green', 'White', 'Pink', 'green']


In [79]:
list=['Red','Green','White','Black','Pink','yellow']
# remove 0th,4th and 5th element from the list
for i in [5, 4, 0]:
    del list[i]
print(list)

['Green', 'White', 'Black']


In [81]:
list=['Red','Green','White','Black','Pink']
# remove 0th,4th and 5th element from the list
for i in [5, 4, 0]:
    del list[i]
print(list)

IndexError: list assignment index out of range

In [85]:
a=[2,3,4]
del a[1]
print(a)

[2, 4]


In [ ]:
Write a Python program to get a list, sorted in increasing order by the last element in each 
tuple from a given list of non-empty tuples.
Sample List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]

In [93]:
a=[(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i][1]>a[j][1]:
            a[i],a[j]=a[j],a[i]
print(a)

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [145]:
for i in range(5):
    for j in range(9):
        if (j==0 and  i==0)or(j==0 and i==2)or(i==1 and 1<=j<=3)or(i>2 and j<=3)or(i<2 and j>4)or(i==3 and 4<j<6)or(i==2 and 4<j<=6)or(i==2 and j==8) or (i==3 and j>=7) or (i==4 and j>=6):
            print(" ",end="")
        else:
            print("*",end="")
    print()

 ****    
*   *    
 ****  * 
    * *  
    **   


In [187]:
for i in range(5):
    for j in range(10):
        if (i==3 and j==0)or(i==1 and j==1) or (i==0 and 2<j<9) or(i==1 and 2<j<8) or (i==3 and 1<j<8) or(i==4 and 0<j<9) or (j==9 and 1<=i<4):
            print(" ",end="")
        else:
            print("*",end="")
    print()

***      *
* *     * 
********* 
 *      * 
*        *


In [17]:
# Dictionary : It is a mapper Datatype
a={'id':3001,'name':"Shivam",'isadhaar':{'IsActive':True,'age':23}}
print(type(a))

<class 'dict'>


In [21]:
print(a['isadhaar']['age'])

23


In [119]:
a={'id':[3001,3002,3003,3004],'name':["Shivam",'Rahul',"Pankaj","Dheeraj"]}

In [35]:
print(a['id'][3])

3004


In [33]:
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']}


In [45]:
print(a.keys())
print(a.values())
print(a.items())

dict_keys(['id', 'name'])
dict_values([[3001, 3002, 3003, 3004], ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']])
dict_items([('id', [3001, 3002, 3003, 3004]), ('name', ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'])])


In [49]:
for i,j in a.items():
    print(i,"   ",j)

id     [3001, 3002, 3003, 3004]
name     ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']


In [59]:
print(a.get('marks'))

None


In [63]:
type(a.items())

dict_items

In [65]:
a.keys()

dict_keys(['id', 'name'])

In [69]:
a.pop('name')

['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']

In [75]:
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']}


In [77]:
a.popitem()

('name', ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'])

In [79]:
print(a)

{'id': [3001, 3002, 3003, 3004]}


In [85]:
a.setdefault('marks',90)

90

In [87]:
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 'marks': 90}


In [109]:
a.update([{'marks',98}])

In [91]:
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 'marks': 98}


In [93]:
a['marks']=65
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 'marks': 65}


In [95]:
a.values()

dict_values([[3001, 3002, 3003, 3004], ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 65])

In [111]:
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 'marks': 98}


In [115]:
num={}
for i in range(1,16):
    num.update([[i,i**2]])
print(num)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [125]:
print(a)
print(num)
a.update(num)
print(a)

{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj']}
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}
{'id': [3001, 3002, 3003, 3004], 'name': ['Shivam', 'Rahul', 'Pankaj', 'Dheeraj'], 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


In [145]:
a={'id':3002,'name':"Pankaj",'address':{'House No':89,'Sector':63,"CIty":"Noida"}}
for i,j in a.items():
    if type(j)==dict:
        print(i)
        for k,l in j.items():
            print(k,"   ",l)
    else:
        print(i,"    ",j)

id      3002
name      Pankaj
address
House No     89
Sector     63
CIty     Noida


In [147]:
a={'a':334,'b':224,'c':996,'d':611}
print("Maximum value of my dictionary is :",max(a.values()))
print("Minimum value of my dictionary is :",min(a.values()))

Maximum value of my dictionary is : 996
Minimum value of my dictionary is : 224


In [149]:
a={'a':334,'b':224,'c':996,'d':611}
max=0
for i in a.values():
    if max<i:
        max=i
print("Maximum value of my dictionary is :",max)
    

Maximum value of my dictionary is : 996


In [ ]:
a={1:10,2:20}
b={3:30,4:40}
c={5:50,6:60}
d={}


In [1]:
a={'id':[3001,3002,3003,3004],'name':["Shivam",'Rahul',"Pankaj","Dheeraj"]}

In [3]:
a=[1,2,3,4,5,6,7,8]
for i in a:
    if i%2==1:
        a.remove(i)
print(a)

[2, 4, 6, 8]


In [5]:
a=[1,2,3,4,5,6,7,8]
a=[x for x in a if x%2==0]
print(a)

[2, 4, 6, 8]


In [9]:
a=[1,2,3,4,5,6,7,8]
a= [x**2 for x in a]
print(a)

[1, 4, 9, 16, 25, 36, 49, 64]


In [11]:
# inbuilt,User Defined Function

In [23]:
def hello(name):
    print("Hello",name)

In [27]:
hello("Pankaj")

Hello Pankaj


In [31]:
def fact(num):
    factorial=1
    while num>=1:
        factorial*=num
        num=num-1
    print(factorial)

In [37]:
fact(5)

120


In [39]:
def fact():
    num=int(input("Enter any Number :"))
    factorial=1
    while num>=1:
        factorial*=num
        num=num-1
    print(factorial)

In [43]:
fact()

Enter any Number : 7


5040


In [45]:
def info(name , age, marks):
    print("hello my name is ",name," and my age is ",age," and I got ",marks,"marks")

In [53]:
info(34,"Kartik",90)

hello my name is  34  and my age is  Kartik  and I got  90 marks


In [55]:
# non-return-type, return-type
def add(a,b,c):
    d=a+b+c
    print(d)

In [67]:
ans=add(56,45,32)
print(type(ans))
print(ans*0.1)

133
<class 'NoneType'>


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [59]:
def add1(a,b,c):
    d=a+b+c
    return d

In [69]:
ans1=add1(56,45,32)
print(type(ans1))
print(ans1*0.1)

<class 'int'>
13.3


In [73]:
# positional Arguments 
def info(name , age, marks):
    print("hello my name is ",name," and my age is ",age," and I got ",marks,"marks")
info(age=34,name="Kartik",marks=90)

hello my name is  Kartik  and my age is  34  and I got  90 marks


In [97]:
# default Arguments 
def info(name="Akash",age=10,marks=98):
    print("hello my name is ",name," and my age is ",age," and I got ",marks,"marks")
info(name="Puja",age=19)

hello my name is  Puja  and my age is  19  and I got  98 marks


In [99]:
def misslaneous(a,b):
    add=a+b
    diff=a-b
    return add,diff

In [101]:
misslaneous(90,78)

(168, 12)

In [103]:
def check_palindrome(a,b):
    if b==a[::-1]:
        return True

In [107]:
check_palindrome("12321","123210")

In [29]:
def check_short(a :list,b :list):
    '''This function will chech if second list is sorted list of first one
     a---> list(datatype)
     b---> list(datatype)'''
    a.sort()
    if b==a:
        return True
    

In [31]:
check_short([1,3,2],[1,2,3])

True

In [25]:
a

[1, 2, 3]

In [19]:
a=[1,3,2]
a.sort()
print(a)

[1, 2, 3]


In [35]:
def countlowerupper(a :str):
    '''This function will count the lowercases and uppercases of the string(a)
    a--->str'''
    upper="QWERTYUIOPASDFGHJKLZXCVBNM"
    lower="qwertyuiopasdfghjklzxcvbnm"
    countupper=0
    countlower=0
    for i in a:
        if i in upper:
            countupper+=1
        elif i in lower:
            countlower+=1
    return countupper,countlower

In [37]:
countlowerupper("This is a python Class")

(2, 16)

In [43]:
# Recursion
def sum_n(n :int):
    if n==0:
        return 0
    return n + sum_n(n-1)

In [45]:
sum_n(10)

55

In [47]:
def factorial(n):
    if n==0:
        return 1
    elif n==1:
        return 1
    return n*factorial(n-1)

In [49]:
factorial(5)

120

In [55]:
def fibbinocci(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    return fibbinocci(n-1)+fibbinocci(n-2)

In [57]:
fibbinocci(10)

55

In [63]:
for i in range(11):
    print(fibbinocci(i))

0
1
1
2
3
5
8
13
21
34
55


In [ ]:
# pascal trinagle 
# tower of hanoi


In [65]:
# decorator -- It is a function that takes argument as function return value as function

In [73]:
def decor(func):
    def wrapper():
        print("Hello Class")
        func()
        print("bye class")
    return wrapper
def func():
    print("Today I will teach Recursion1 and decorator1")
de=decor(func)
de()

Hello Class
Today I will teach Recursion1 and decorator1
bye class


In [19]:
pascal=[]
element=[1]
answer=[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
i=0
while i<5:
    temp=element.copy()
    temp.insert(0,0)
    temp.append(0)
    element=[]
    for i in range(1,len(temp)):
        sum=temp[i-1]+temp[i]
        element.append(sum)
    # print(temp)
        print(element)
    i=i+1

[1, 1]
[1, 1, 1]
[1, 1, 1, 1]
[1, 1, 1, 1, 2]
[1, 1, 1, 1, 2, 2]
[1, 1, 1, 1, 2, 2, 1]


In [13]:
element=[1]
temp=element.copy()
temp.insert(0,0)
temp.append(0)
print(element)
print(temp)

[1]
[0, 1, 0]


In [26]:
pascal=[]
element=[1]
answer=[[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]
i=0
n=7
while i<n:
    pascal.append(element)
    temp=element.copy()
    temp.insert(0,0)
    temp.append(0)
    element=[]
    for j in range(1,len(temp)):
        sum=temp[j-1]+temp[j]
        element.append(sum)
    i=i+1
for i in range(len(pascal)):
    for k in range(n-i):
        print(" ",end="")
    for j in range(len(pascal[i])):
        print(pascal[i][j],end=" ")
    print()

       1 
      1 1 
     1 2 1 
    1 3 3 1 
   1 4 6 4 1 
  1 5 10 10 5 1 
 1 6 15 20 15 6 1 


In [56]:
def tower_of_hanoi(n,a,b,c):
    if n==1:
        print("move 1st disk from",a ,"to", c)
        return
    tower_of_hanoi(n-1,a,c,b)
    print(" move" ,n,"th disk from ",a ,"to",c)
    tower_of_hanoi(n-1,b,a,c)
    # print(" move" ,n,"th disk from ",c ,"to",b)

In [62]:
tower_of_hanoi(4,"s","h","d")

move 1st disk from s to h
 move 2 th disk from  s to d
move 1st disk from h to d
 move 3 th disk from  s to h
move 1st disk from d to s
 move 2 th disk from  d to h
move 1st disk from s to h
 move 4 th disk from  s to d
move 1st disk from h to d
 move 2 th disk from  h to s
move 1st disk from d to s
 move 3 th disk from  h to d
move 1st disk from s to h
 move 2 th disk from  s to d
move 1st disk from h to d


In [6]:
# Write a Python function that uses a ternary operator to check if a number is within a specified range and returns a custom message.

a=range(1,10)
b=lambda x :"Yes" if x in a else "No"
print(b(11))

No


In [2]:
# decorator
# lamda
a= lambda x,y:x+y
print(a(3,67))

70


In [8]:
a=[1,2,3,4,5,6,7,8]
def filterlist(a :list):
    b=[]
    for i in a:
        if i%2==0:
            b.append(i)
    return b

In [10]:
filterlist([1,2,3,4,5,6,7,8])

[2, 4, 6, 8]

In [14]:
# filter
a=[1,2,3,4,5,6,7,8]
b=list(filter(lambda x:x%2==0,a))
print(b)

[2, 4, 6, 8]


In [18]:
a=[1,2,3,4,5,6,7,8]
a=[x for x in a if x%2==0]
print(a)

[2, 4, 6, 8]


In [24]:
# map
a=[1,2,3,4,5,6,7,8]
b=list(map(lambda x:x**3,a))
print(b)

[1, 8, 27, 64, 125, 216, 343, 512]


In [30]:
#reduce
from functools import reduce
a=[1,2,3,4,5,6,7,8]
b=reduce(lambda x,y:x+y,a)
print(b)

36


In [32]:
a=[1,2,3,4,5,6,7,8]
b=0
for i in range(len(a)):
    b+=a[i]
print(b)

36


In [42]:
def cal_per(a,b,c):
    avg=(a+b+c)/3
    return avg

In [46]:
cal_per(90,57,89,89,31)

TypeError: cal_per() takes 3 positional arguments but 5 were given

In [56]:
def cal_per(*args):
    print(type(args))
    avg=sum(args)/len(args)
    return avg

In [58]:
cal_per(90,57,89,89,31)

<class 'tuple'>


71.2

In [74]:
def cal_per(**kwargs):
    '''This is example kwargs(**)'''
    print(type(kwargs))
    print(kwargs)
    avg=sum(kwargs.values())/len(kwargs)
    return avg

In [76]:
cal_per(mohit=78,Nisha=90,Lokesh=100)

<class 'dict'>
{'mohit': 78, 'Nisha': 90, 'Lokesh': 100}


89.33333333333333

In [100]:
# decorator:it is function that takes argument as function and raturn value as function
def main(func):
    def operation():
        def hero():
            print("This is wrapper function class")
            func()
            print(" We are learning decorator")
        return hero
    return operation

def func():
    print(" I am lokesh")
# main(func)()()
my_decorator=main(func)
my_decorator()()

This is wrapper function class
 I am lokesh
 We are learning decorator


In [114]:
def main(func):
    def operation():
        print("This is wrapper function class")
        func()
        print(" We are learning decorator")
    return operation
@main
def func():
    print(" I am lokesh")
func()

This is wrapper function class
 I am lokesh
 We are learning decorator


In [ ]:
# Create a Chain of Function Decorators (Bold, Italic, Underline, etc.)

# Write a Python program to create a chain of function decorators (bold, italic, underline etc.
def decor(func):
    def wrapper():
        func()
        return func
    return wrapper

In [ ]:
Second Lowest Grade Lambda

Write a Python program to find the second lowest total marks of any student(s) from the given names and marks of each student using lists and lambda. Input the number of students, the names and grades of each student.

Input number of students: 5
Name: S ROY
Grade: 1
Name: B BOSE
Grade: 3
Name: N KAR
Grade: 2
Name: C DUTTA
Grade: 1
Name: G GHOSH
Grade: 1
Names and Grades of all students:
[['S ROY', 1.0], ['B BOSE', 3.0], ['N KAR', 2.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0]]
Second lowest grade: 2.0
Names:
N KAR

In [9]:
a=[['S ROY', 1.0], ['B BOSE', 3.0], ['N KAR', 2.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0]]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i][1]>a[j][1]:
            a[j],a[i]=a[i],a[j]
print(a)

[['S ROY', 1.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0], ['N KAR', 2.0], ['B BOSE', 3.0]]


In [27]:
a=[['S ROY', 1.0], ['B BOSE', 3.0], ['N KAR', 2.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0]]
b=set()
for i in range(len(a)):
    b.add(a[i][1])
c=list(b)
c.sort()
print("second lowest element is :",c[1])
for i in range(len(a)):
    if c[1]==a[i][1]:
        print(a[i][0])

second lowest element is : 2.0
N KAR


In [43]:
a=[['S ROY', 1.0], ['B BOSE', 3.0], ['N KAR', 2.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0]]
b=sorted(a , key= lambda x : x[1])
print(b)

[['S ROY', 1.0], ['C DUTTA', 1.0], ['G GHOSH', 1.0], ['N KAR', 2.0], ['B BOSE', 3.0]]


In [45]:
# Define a string variable 'mycode' containing a Python code as a string
mycode = 'print("hello world")'

# Define a multi-line string variable 'code' containing Python code as a string
code = """
def mutiply(x,y):
    return x*y

print('Multiply of 2 and 3 is: ',mutiply(2,3))
"""

# Execute the Python code represented by the string stored in the variable 'mycode'
exec(mycode)

# Execute the Python code represented by the multi-line string stored in the variable 'code'
exec(code) 


hello world
Multiply of 2 and 3 is:  6


In [49]:
# Write a Python function that uses dictionary keys to preserve order while filtering out duplicate elements from a list.
a=[1,2,2,3,4,5,5,5,5,5,5,8]
b=[]
# for i in range(len(a)):
for i in a:
    if i not in b:
        b.append(i)
print(b)

[1, 2, 3, 4, 5, 8]


In [57]:
a=[1,2,2,3,4,5,5,5,5,5,5,8]
b={}
for i in range(len(a)):
    b.update([(a[i],a.count(a[i]))])
print(b)

{1: 1, 2: 2, 3: 1, 4: 1, 5: 6, 8: 1}


In [51]:
a=[1,2,2,3,4,5,5,5,5,5,5,8]
for i in a:
    if a.count(i)>=2:
        print(i)

2
2
5
5
5
5
5
5


In [63]:
a=[1,2,2,3,4,5,5,5,5,5,5,8]
a=list(set([x for x in a if a.count(x)>=2]))
print(a)

[2, 5]


In [1]:
# Class and Object
a=[1,2,2,5,5]

In [7]:
print(type(a))

<class 'list'>


In [81]:
class My_class:
    a="Shivam"
    b="Maurya"
    c="Abhishek"
    def conc(self):
        return self.a+" "+self.b
    def mult(self,count):
        return self.c*count

In [83]:
myclass=My_class()

In [95]:
myclass.a
myclass.b
myclass.conc()

'Shivam Maurya'

In [97]:
myclass.mult(5)

'AbhishekAbhishekAbhishekAbhishekAbhishek'

In [103]:
class My_class:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
    def conc(self):
        return self.a+" "+self.b
    def mult(self,count):
        return self.c*count

In [105]:
myclass=My_class("Abhishek","Suman",90)

In [107]:
myclass.a
myclass.b
myclass.conc()

'Abhishek Suman'

In [109]:
myclass.mult(5)

450

In [111]:
class My_calculation:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def addition(self):
        return self.a+self.b
    def subtraction(self):
        return self.a-self.b
    def product(self):
        return self.a*self.b  
    def division(self):
        return self.a/self.b

In [113]:
my=My_calculation(45,21)

In [115]:
print(my.addition())
print(my.division())
print(my.product())
print(my.subtraction())

66
2.142857142857143
945
24


In [119]:
My_calculation(45,21).addition()

66

In [137]:
# Encapsulation,Inheritance,Polymorphism,Abstraction
class Bank:
    def __init__(self,name,acc_no,balance):
        self.name=name
        self.acc_no=acc_no
        self.__balance=balance
    def detail(self):
        print("The acoount number is ",self.acc_no)
        print("The acoount holder name is ",self.name)
        print("The acoount balance is ",self.__balance)
        

In [139]:
bank=Bank("Shubham",12345,8000)

In [141]:
bank.detail()

The acoount number is  12345
The acoount holder name is  Shubham
The acoount balance is  8000


In [51]:
# Inheritance
# Simple
class Parent:
    def farming_land(self):
        print("I have 100 acres land for farming")
    def vehicle(self):
        print(" I have Tractor and Sedan Car")
class Child(Parent):
    def flat(self):
        self.farming_land()
        print("i have 2 bhk flat in Noida")
    def car(self):
        print("I have a Fortuner car")

In [53]:
pa=Parent()
ch=Child()

In [55]:
ch.flat()

I have 100 acres land for farming
i have 2 bhk flat in Noida


In [31]:
# multiple Inheritance
class Parent:
    def farming_land(self):
        print("I have 100 acres land for farming")
    def vehicle(self):
        print(" I have Tractor and Sedan Car")
class Child:
    def flat(self):
        print("i have 2 bhk flat in Noida")
    def car(self):
        print("I have a Fortuner car")
class Grand_son(Parent,Child):
    def toy(self):
        print("I have a elephant toy")
    def bicyle(self):
        print("I have triclyle Also")

In [33]:
gs=Grand_son()

In [35]:
gs.toy()

I have a elephant toy


In [37]:
# multilevel ingeritance
class Parent:
    def farming_land(self):
        print("I have 100 acres land for farming")
    def vehicle(self):
        print(" I have Tractor and Sedan Car")
class Child(Parent):
    def flat(self):
        print("i have 2 bhk flat in Noida")
    def car(self):
        print("I have a Fortuner car")
class Grand_son(Child):
    def toy(self):
        print("I have a elephant toy")
    def bicyle(self):
        print("I have triclyle Also")

In [41]:
gs=Grand_son()

In [43]:
# Herarichal Inheritance
class Parent:
    def farming_land(self):
        print("I have 100 acres land for farming")
    def vehicle(self):
        print(" I have Tractor and Sedan Car")
class Child(Parent):
    def flat(self):
        print("i have 2 bhk flat in Noida")
    def car(self):
        print("I have a Fortuner car")
class Grand_son(Parent):
    def toy(self):
        print("I have a elephant toy")
    def bicyle(self):
        print("I have triclyle Also")

In [85]:
class Bank:
    def __init__(self,name,acc_no,balance):
        self.name=name
        self.acc_no=acc_no
        self.__balance=balance
    def deposit(self,amount):
        if amount>0:
            self.__balance+=amount
            print(f"You have deposited {amount} and now your balance is {self.__balance}")
        else:
            print("Enter valid amount")
    def withdrawl(self,amount):
        if amount<=self.__balance:
            self.__balance-=amount
            print(f"You have withdrawn {amount} and now your balance is {self.__balance}")
        else:
            print("Insufficient Balance is in your account")
    def detail(self):
        print("The acoount number is ",self.acc_no)
        print("The acoount holder name is ",self.name)
        print("The acoount balance is ",self.__balance)
class BankInterest(Bank):
    def __init__(self,name,acc_no,balance,intereset_rate=0.04):
        super().__init__(name,acc_no,balance)
        self.intereset_rate=intereset_rate
    def claculate_interest(self):
        self.__balance=self.__balance+(self.__balance*self.intereset_rate)
        print("Now you balance is after adding the interest :",self.__balance)


In [87]:
bi=BankInterest("Pankaj","12345",20000)

In [89]:
bi.claculate_interest()

AttributeError: 'BankInterest' object has no attribute '_BankInterest__balance'

In [91]:
bi.deposit(10000)

You have deposited 10000 and now your balance is 30000


In [93]:
bi.withdrawl(4500)

You have withdrawn 4500 and now your balance is 25500


In [95]:
class Bank:
    def __init__(self,name,acc_no,balance):
        self.name=name
        self.acc_no=acc_no
        self._balance=balance
    def deposit(self,amount):
        if amount>0:
            self._balance+=amount
            print(f"You have deposited {amount} and now your balance is {self._balance}")
        else:
            print("Enter valid amount")
    def withdrawl(self,amount):
        if amount<=self._balance:
            self._balance-=amount
            print(f"You have withdrawn {amount} and now your balance is {self._balance}")
        else:
            print("Insufficient Balance is in your account")
    def detail(self):
        print("The acoount number is ",self.acc_no)
        print("The acoount holder name is ",self.name)
        print("The acoount balance is ",self._balance)
class BankInterest(Bank):
    def __init__(self,name,acc_no,balance,intereset_rate=0.04):
        super().__init__(name,acc_no,balance)
        self.intereset_rate=intereset_rate
    def claculate_interest(self):
        self._balance=self._balance+(self._balance*self.intereset_rate)
        print("Now you balance is after adding the interest :",self._balance)

In [98]:
bi=BankInterest("Pankaj","12345",20000)

In [100]:
bi.claculate_interest()

Now you balance is after adding the interest : 20800.0


In [33]:
a=[10,10,0,0,10]
temp=a*2
# b=[10,10,10,0,0]
# a=[10,10,0,0,10]
b=[10,10,0,0,10]
# b=[1,10,10,0,10]
count=0
tempi=0
for i in range(len(temp)):
    for j in range(tempi,len(b)):
        if temp[i]==b[j]:
            count=count+1
            tempi+=1
        elif temp[i]!=b[j]:
            count=0
        break     
if count==5:
    print("identetical")

identetical


In [5]:
print(a==b)

False


In [13]:
a=[10,10,0,0,10]*2
print(a)

[10, 10, 0, 0, 10, 10, 10, 0, 0, 10]


In [49]:
a=[10,10,0,0,10]
temp=a*3
# b=[10,10,10,0,0]
# a=[10,10,0,0,10]
b=[10,0,0,10,10]
# b=[1,10,10,0,10]
count=0
tempi=0
for i in range(len(temp)):
    for j in range(tempi,len(b)):
        if temp[i]==b[j]:
            count=count+1
            tempi+=1
        elif temp[i]!=b[j]:
            count=0
        break     
if count==5:
    print("identetical")
print(count)

4


In [51]:
print(temp)

[10, 10, 0, 0, 10, 10, 10, 0, 0, 10, 10, 10, 0, 0, 10]


In [59]:
a=[10,10,0,0,10]
b=""
for i in a:
    b=b+str(i)
print(b*2)

1010001010100010


In [61]:
c=b*2
print(c)

1010001010100010


In [67]:
li=[1,10,10,0,10]
d=""
for i in li:
    d=d+str(i)


In [69]:
if d in c:
    print("idntitical")

In [5]:
# polymorphism
class Main:
    def hello(self):
        print(" Hello Class")
    def hello(self,name):
        print("Hello",name)
class sub(Main):
    def hello(self):
        print("Hello Noida")

In [7]:
mn=Main()

In [9]:
sb=sub()

In [11]:
sb.hello()

Hello Noida


In [85]:
# Abstraction
from abc import ABC,abstractmethod
class Admin(ABC):
    @abstractmethod
    def security(self):
        pass
    @abstractmethod
    def authentication(self):
        pass
class Web(Admin):
    def security():
        print("I am following the security concerns")
    def authentication():
        print("I am following the authentication also")
    def transaction(self):
        print("You are doing transaction from web")
class APP(Admin):
    def security():
        print("I am following the security concerns")
    def authentication(self):
        print("I am following the authentication also")
    def transaction(self):
        print("You are doing transaction from Mobile Application")

In [87]:
app=APP()

In [91]:
app.authentication()

I am following the authentication also


In [75]:
wb=Web()

In [93]:
# module
# math, datetime,random,os
import math

In [95]:
math.factorial(6)

720

In [99]:
math.sqrt(64)

8.0

In [103]:
math.gcd(8,64,32)

8

In [108]:
from datetime import datetime

In [110]:
datetime.today()

datetime.datetime(2025, 11, 22, 13, 2, 2, 953513)

In [114]:
datetime.weekday(datetime.today())

5

In [118]:
# datetime.replace(datetime.today())

In [120]:
import random

In [128]:
a=["sonu",'monu','kartik']
random.choice(a)

'sonu'

In [178]:
li=[]
for i in range(5):
    a=random.randint(2,200)
    li.append(a)
print(li)

[41, 134, 103, 7, 37]


In [180]:
print(a)

37


In [182]:
random.shuffle(li)

In [184]:
print(li)

[134, 37, 103, 7, 41]


In [186]:
import module

In [188]:
module.ss(6,8)

100

In [7]:
from module import My_module

In [ ]:
my_module.

In [5]:
from module import *

In [19]:
from module.My_module import *

ModuleNotFoundError: No module named 'module.My_module'; 'module' is not a package

In [17]:
ym.add_string('abc','sonu','nikil')

'abcsonunikil'

In [17]:
%%writefile my_module.py

# my_module.py

def greet(name):
    """
    This function greets the person passed in as a parameter.
    """
    return f"Hello, {name}!"

def farewell(name):
    """
    This function bids farewell to the person.
    """
    return f"Goodbye, {name}!"
def exam(name):
    return f"get ready from exam {name}"

Overwriting my_module.py


In [19]:
# from my_module import 
import my_module

In [33]:
my_module.farewell("Kaushik")

'Goodbye, Kaushik!'

In [23]:
greet("Aman")

NameError: name 'greet' is not defined

In [25]:
exam("Seema")

NameError: name 'exam' is not defined

In [37]:
from module import Your_module

In [ ]:
module.Your_module.add_string

In [39]:
Your_module.add_string('abc','xyz')

'abcxyz'

In [41]:
Your_module.mro()

[module.Your_module, object]

In [73]:
from my_package import circle,triangle,recteangle

In [61]:
circle.area(4.5)

63.585

In [69]:
circle.parameter(54)

339.12

In [75]:
triangle.area(2,3,4)

2.9047375096555625

In [77]:
# File handling
a=open('abhishek.txt',"x")

In [87]:
a=open('abhshek.txt','a')
a.write("\nand we are append the content in the text file")
a.close()

In [89]:
a=open('abhshek.txt','r')
print(a.read())


This is  a file handling  Class and we are writing in the file
and we are append the content in the text file


In [3]:
from datetime import datetime

In [29]:
a=datetime.today()

In [7]:
print(a)

2025-11-29 12:05:10.771755


In [31]:
dob="2000-01-01"

In [33]:
print(dob.date())

AttributeError: 'str' object has no attribute 'date'

In [35]:
dob=datetime.strptime(dob, "%Y-%m-%d")

In [21]:
print(dob)

2000-01-01 00:00:00


In [39]:
diff = relativedelta(date2, date1)
print(f"{diff.years} years, {diff.months} months, {diff.days} days")=a-dob

In [47]:
from dateutil.relativedelta import relativedelta
diff = relativedelta(a, dob)
print(f"{diff.years} years, {diff.months} months, {diff.days} days")

25 years, 10 months, 28 days


In [299]:
# Write a Python program to create a class representing a shopping cart. Include methods for adding and removing items,
# and calculating the total price. 
class Shopping_Cart
    def __init__(self,cart={},**kwargs):
        self.kwargs=kwargs
        self.cart=cart
    def show_list(self):
        for i,j in self.kwargs.items():
            print(i,"   ",j)
    def adding(self):
        for i,j in self.kwargs.items():
            print(i,"   ",j)
        items=list(self.kwargs.keys())
        choice=int(input("Which product do you want to add in cart :"))  
        qty=int(input("Quantity :"))  
        if qty<=self.kwargs[items[choice]][0]:
            self.kwargs[items[choice]][0]-=qty
            self.cart.update([(items[choice],qty)])
        print(self.cart)
    def remove(self):
        for i,j in self.cart.items():
            print(i,j)
        items=list(self.cart.keys())
        user_choice=input("Do you want to remove the product or quatinty[product,quantity] :")
        if user_choice=='product':
            choice=int(input("Which product do you want to remove from the cart :")) 
            self.cart.remove(items[choice])
        elif user_choice=='quantity':
            for i in range(len(items)):
                print(items[i])
            user_product=input("Enter the product from which you want to remove quantity")
            user_quantity=int(input("Enter the quantity"))
            if user_quantity>0 and user_quantity<=self.cart[user_product]:
                self.cart[user_product]-=user_quantity
                self.kwargs[user_product][0]+=user_quantity
        else:
            print("Give correct input")
        print(self.cart)
        print(self.kwargs)
    def price_calculator(self):
        price=0
        for i,j in self.cart.items():
            price=price+(j*self.kwargs[i][1])
        print("Total Price",price)  

In [301]:
sc=Shopping_Cart(Pant=[12,700],Shirt=[30,800])

In [303]:
sc.kwargs

{'Pant': [12, 700], 'Shirt': [30, 800]}

In [305]:
sc.kwargs['Pant'][0]

12

In [307]:
list(sc.kwargs.keys())

['Pant', 'Shirt']

In [309]:
sc.show_list()

Pant     [12, 700]
Shirt     [30, 800]


In [311]:
sc.adding()

Pant     [12, 700]
Shirt     [30, 800]


Which product do you want to add in cart : 0
Quantity : 5


{'Pant': 5}


In [271]:
sc.remove()

Pant 5


Do you want to remove the product or quatinty[product,quantity] : quantity


Pant


Enter the product from which you want to remove quantity Pant
Enter the quantity 3


{'Pant': 2}
{'Pant': [10, 700], 'Shirt': [30, 800]}


In [279]:
a={}
a['shivani']=89
print(a)

{'shivani': 89}


In [313]:
sc.price_calculator()

Total Price 3500


In [3]:
# Wap to pasting vowel from one file to another file
with open('abhshek.txt','r') as file:
    print(file.read())

This is  a file handling  Class and we are writing in the file
and we are append the content in the text file


In [5]:
f=open("abhshek.txt",'r')
print(f.read())

This is  a file handling  Class and we are writing in the file
and we are append the content in the text file


In [23]:
with open("abhshek.txt",'r') as file, open('abhishek.txt','a')as file1:
    content=file.read()
    vow="AEIOUaeiou"
    for i in content:
        if i in vow:
            file1.write(i)
    file1.close()
    file.close()
with open("abhshek.txt",'r') as file, open('abhishek.txt','r')as file1:
    print(file.read())
    print(file1.read())
    file1.close()
    file.close()

This is  a file handling  Class and we are writing in the file
and we are append the content in the text file
iiaieaiaaeaeiiieieaeaeaeeoeieeieiiaieaiaaeaeiiieieaeaeaeeoeieeieiiaieaiaaeaeiiieieaeaeaeeoeieeie


In [25]:
import os

In [29]:
f=open('abhshek.txt','r')
f.read()
f.close()
os.remove("abhshek.txt")

In [31]:
f=open('abhshek.txt','r')
f.read()

FileNotFoundError: [Errno 2] No such file or directory: 'abhshek.txt'

In [33]:
os.rmdir('my_package')

OSError: [WinError 145] The directory is not empty: 'my_package'

In [39]:
import shutil
shutil.rmtree('my_package')

In [43]:
os.remove(r"C:\Users\ANJANA\Downloads\Data Science Weekend Batch (7).ipynb")

In [55]:
# with open("abhshek.txt",'w') as file:
#     file.writelines(["hello","\nLokesh",'\nGoodbye'])
f=open("abhshek.txt",'r')
# print(f.read())
# # print(f.readline())
# print(f.readlines())

In [65]:
# seek,tell
f.seek(5)
f.read(10)

'\nLokesh\nGo'

In [67]:
f.tell()

17

In [ ]:
# text,csv,excel,json,api,sql,web
# pandas
# Exception Handling
valueError,Syntaxerror,ZeroDivisionError,filenotfound,IndexError,AttributeError,nameerror,typeerror,moduleerror

In [71]:
a=[1,2]
print(a[7])


IndexError: list index out of range

In [73]:
print('abc'+90)

TypeError: can only concatenate str (not "int") to str

In [75]:
import ose

ModuleNotFoundError: No module named 'ose'

In [91]:
try:
    print(9/0)
except(ZeroDivisionError) as e:
    print(e)

division by zero


In [89]:
print(9/0)

ZeroDivisionError: division by zero

In [99]:
try:
    a=[1,2,3]
    for i in range(6):
        print(a[i])
except(IndexError) as b:
    print("Error :", b)

1
2
3
Error : list index out of range


In [21]:
try:
    a=int(input("Enter any input :"))
    b=int(input("Enter any input :"))
    print(a/b)
except(ZeroDivisionError,ValueError) as e:
    print("Error",e)

Enter any input : 67
Enter any input : 0


Error division by zero


In [9]:
print(6+'h')

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [27]:
a={'a':1}
print(a['b'])

KeyError: 'b'

In [31]:
try:
    a=int(input("Enter any input :"))
    b=int(input("Enter any input :"))
    print(a/b)
except(ZeroDivisionError,ValueError) as e:
    print("Error",e)
else:
    print(88+90)
    

Enter any input : 56
Enter any input : 0


Error division by zero


In [35]:
try:
    a=int(input("Enter any input :"))
    b=int(input("Enter any input :"))
    print(a/b)
except(ZeroDivisionError,ValueError) as e:
    print("Error",e)
finally:
    print(88+90)

Enter any input : 90
Enter any input : 0


Error division by zero
178


In [37]:
age = -1
if age < 0:
    print("hey ")

hey 


In [43]:
age = -1
if age < 0:
    raise ValueError("Age cannot be negative")

ValueError: Age cannot be negative

In [49]:
class lokeshkierror(Exception):
    pass

age = -1
if age < 0:
    raise lokeshkierror("Custom exception thrown")


lokeshkierror: Custom exception thrown

##hello how are you

In [56]:
x = 9
assert x > 10, "x must be greater than 10"

AssertionError: x must be greater than 10

In [62]:
try :
    a=int(input("Enter any number"))
    print(a)
except KeyboardInterrupt:
    print("Input Dalo")

Input Dalo


Enter any number 78


In [68]:
class Exp:
    def Exceptionerror(self):
        try:
            f=open('shlok.txt','r')
            print(f.read())
        except (FileNotFoundError) as e:
            print(e)
Exp().Exceptionerror()

[Errno 2] No such file or directory: 'shlok.txt'


In [1]:
# thirt-party Module : Numpy,Pandas, matplotlib,Seaborn,Scikitlearn,Tensorflow,nltk,Keras
# Numpy:It is collection of elements with similar datatype and same size
# Numpy:Numerical Python
import numpy as np

In [3]:
a=np.array([1,2,3,4,5,6])
print(a+5)

[ 6  7  8  9 10 11]


In [5]:
li=[1,2,3,4,5,6]
li=[x+5 for x in li]
print(li)

[6, 7, 8, 9, 10, 11]


In [7]:
a=np.array([1,2,3,4,5,6,2147483648],dtype='float')
print(a.dtype)

float64


In [9]:
b=np.log10(a)
print(b)
print(b.dtype)

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 9.33192987]
float64


In [33]:
a=np.array([1,2,3,4,5,6])
b=np.array([5,6,7,8,9,10])
print(a+b)
print(a.ndim)
print(a.shape)
print(len(a))
print(type(a))
print(a[-4:-2])
a[4]=90
print(a)

[ 6  8 10 12 14 16]
1
(6,)
6
<class 'numpy.ndarray'>
[3 4]
[ 1  2  3  4 90  6]


In [65]:
a=np.array([[1,2,3,4],[4,5,6,7],[44,55,66,77]])
print(a)
print(a.ndim)
print(a.shape)
print(a[1,2])
print(a[2,2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [44 55 66 77]]
2
(3, 4)
6
66


In [53]:
a=np.array(6)
print(a.shape)
print(a.ndim)

()
0


In [57]:
b=[[1,2,3,4],[4,5,6,7],[44,55,66,77]]
print(type(b))
print(b[1][2])

<class 'list'>
6


In [73]:
a=np.array([[1,2,3,4],[4,5,6,7],[44,55,66,77]])
print(a)
print(a.ndim)
print(a.shape)
print(a[2,2:])
print(a[1:,1:3])
print(a[:,:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [44 55 66 77]]
2
(3, 4)
[66 77]
[[ 5  6]
 [55 66]]
[[ 1  2]
 [ 4  5]
 [44 55]]


In [87]:
a=np.array([[1,2,3],[4,5,6],[44,55,66],[444,555,666]],ndmin=3)
print(a)
print(a.shape)

[[[  1   2   3]
  [  4   5   6]
  [ 44  55  66]
  [444 555 666]]]
(1, 4, 3)


In [119]:
a=np.array([[[1,2,3,30],[4,5,6,40],[7,8,9,100]],[[10,20,30,90],[11,12,13,111],[7,8,9,49]],[[100,200,300,59],[110,120,130,69],[7,8,9,88]]])
print(a.shape)
print(a)
print(a[1,1,1])
print(a[2,1,2])
print(a[2,0,:])
print(a[:,0,1])
print(a[:,1,1:])
print(a[:,0,1:3])
print(a[:2,:2,1:])
print(a[:,:,:2])

(3, 3, 4)
[[[  1   2   3  30]
  [  4   5   6  40]
  [  7   8   9 100]]

 [[ 10  20  30  90]
  [ 11  12  13 111]
  [  7   8   9  49]]

 [[100 200 300  59]
  [110 120 130  69]
  [  7   8   9  88]]]
12
130
[100 200 300  59]
[  2  20 200]
[[  5   6  40]
 [ 12  13 111]
 [120 130  69]]
[[  2   3]
 [ 20  30]
 [200 300]]
[[[  2   3  30]
  [  5   6  40]]

 [[ 20  30  90]
  [ 12  13 111]]]
[[[  1   2]
  [  4   5]
  [  7   8]]

 [[ 10  20]
  [ 11  12]
  [  7   8]]

 [[100 200]
  [110 120]
  [  7   8]]]


In [123]:
# copy,view
a=np.array([1,2,3,4,5,6])
b=a.copy() #shallow copy
b[3]=90
print(a)
print(b)

[1 2 3 4 5 6]
[ 1  2  3 90  5  6]


In [143]:
a=np.array([1,2,3,4,5,6])
b=a.view() #deep copy
b[3]=90
print(a)
print(b)

[ 1  2  3 90  5  6]
[ 1  2  3 90  5  6]


In [129]:
class abc:
    def hello(self):
        print("Hello")

In [133]:
abc()

In [137]:
a()

TypeError: 'numpy.ndarray' object is not callable

In [145]:
print(id(a))

1957756838384


In [147]:
print(id(b))

1957756840880


In [1]:
import numpy as np

In [3]:
a=np.array([22,23,34,78])
print(a)

[22 23 34 78]


In [5]:
a=np.random.rand(50)
print(a)

[0.20228767 0.02504649 0.46621013 0.97534373 0.91369698 0.25021395
 0.29911538 0.13813126 0.35395414 0.51188947 0.92619327 0.81088427
 0.3736121  0.11533889 0.62063766 0.78462918 0.34794076 0.1113867
 0.89950746 0.83284029 0.25477153 0.26233973 0.0266701  0.98091509
 0.54717244 0.98420837 0.96219257 0.63601145 0.09222036 0.01939534
 0.02527494 0.69817957 0.13236403 0.91411489 0.04644755 0.52995169
 0.44334651 0.59000592 0.15760275 0.13243774 0.29251533 0.08691999
 0.49432323 0.07521224 0.22297029 0.91222777 0.5632108  0.26269079
 0.17303336 0.84003302]


In [48]:
a=np.random.randint(1,100,25)
print(a)

[ 1 14 49 42 76 55 41 81 94 31 36 83 63 89 31  7 36 38 23  7  7 22 66 16
 75]


In [13]:
a=np.arange(1,51,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [17]:
a=np.linspace(0,20,7)
print(a)

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]


In [21]:
a

array([51, 39, 63, 66, 32, 99, 82, 70, 72,  1, 32, 78, 26, 55, 22, 86, 29,
       59, 50, 44, 11, 90, 92, 89,  5])

In [32]:
np.mean(a)

53.72

In [25]:
np.median(a)

55.0

In [58]:
a=np.sort(a)

In [40]:
print(len(a))

25


In [60]:
a

array([ 1,  7,  7,  7, 14, 16, 22, 23, 31, 31, 36, 36, 38, 41, 42, 49, 55,
       63, 66, 75, 76, 81, 83, 89, 94])

In [50]:
np.min(a)

1

In [52]:
np.max(a)

94

In [62]:
# 25,50,75%
np.quantile(a,0.5)

38.0

In [ ]:
# zero matrix, ones matrix, identity Matrix,eye matrix

In [72]:
a=np.zeros((2,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [82]:
# [[1,0,1,0,1,0,1,0],
#  [0,1,0,1,0,1,0,1],
#  [1,0,1,0,1,0,1,0],
#  [0,1,0,1,0,1,0,1]]
a=np.zeros((4,8))
a[::2,::2]=1
a[1::2,1::2]=1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [90]:
# [[1,1,1,1,1,1,1,1],
#  [1,0,0,0,0,0,0,1],
#  [1,0,0,0,0,0,0,1],
#  [1,1,1,1,1,1,1,1]]
a=np.ones((4,8))
a[1:3,1:7]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [94]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [102]:
a=np.eye(3,3,k=-1)
print(a)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [114]:
a=np.array([1,2,3])
b=np.array([7,8,9])
np.stack([a,b],axis=1)

array([[1, 7],
       [2, 8],
       [3, 9]])

In [142]:
# reshapping the Array
a=np.arange(30)
b=a.reshape(2,5,3)
print(b)
c=b.reshape(5,6)
c.reshape(-1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [148]:
a=np.ones((3,3))
b=np.zeros((3,3))
c=np.stack([a,b],axis=0)
d=np.stack([a,b],axis=1)
print(a)
print(b)
print(c)
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,4,2,60])
print(np.intersect1d(a,b))

[2 4 5]


In [11]:
a=np.array([[6,7,3,9],[3,4,1,8],[7,8,1,4]])
print(a)
print(np.sort(a,axis=0))
print(np.sort(a,axis=1))

[[6 7 3 9]
 [3 4 1 8]
 [7 8 1 4]]
[[3 4 1 4]
 [6 7 1 8]
 [7 8 3 9]]
[[3 6 7 9]
 [1 3 4 8]
 [1 4 7 8]]


In [17]:
var1=np.matrix([[1,2],[3,4]])
print(var1)
print(np.swapaxes(var1,0,1))
# print(np.swapaxes(var,1,0))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
