In [15]:
import numpy as np
v=np.array([2,5,4,9,3,8])
v

array([2, 5, 4, 9, 3, 8])

In [16]:
np.var(v)

np.float64(6.472222222222222)

In [21]:
np.std(v)

np.float64(2.544056253745625)

In [17]:
m=np.mean(v)
m

np.float64(5.166666666666667)

In [18]:
y=m-v
y

array([ 3.16666667,  0.16666667,  1.16666667, -3.83333333,  2.16666667,
       -2.83333333])

In [19]:
b=y**2
b

array([10.02777778,  0.02777778,  1.36111111, 14.69444444,  4.69444444,
        8.02777778])

In [20]:
u=np.sum(b)/len(v)
u

np.float64(6.472222222222222)

In [22]:
c=np.sqrt(u)
c

np.float64(2.544056253745625)

In [ ]:
# x=np.array([5,10,5,11,12,4,3,2,7,1])
# y=np.array([1,6,2,8,5,1,4,6,5,2