In [5]:
# Variable
s=10

In [6]:
s

10

In [7]:
# Constraint
PI=3.14

In [9]:
PI

3.14

In [10]:
x=123
type(x)

int

In [11]:
x='Chandan'
type(x)

str

In [13]:
x=True
type(x)

bool

In [14]:
x=1.34
type(x)

float

In [19]:
x='A'
type(x)  

str

In [18]:
h=[1,2,3,4,5,6,7,8]
type(h)

list

In [22]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [23]:
# Control structure
# Decision making  -- if, else, 
# looping         -- for ,while
# Jumping        -- break, continue ,pass 

In [2]:
num=int(input("Enter the number"))
if num%5==0:
    print("Number is divisible by 5")
else:
    print("Number is not divisible by 5")

Enter the number 78


Number is not divisible by 5


In [1]:
# odd or Even
num=int(input("Enter the number"))
if num%2==0:
    print("number is even")
else:
    print("number is odd ")

Enter the number 25


number is odd 


In [26]:
age=int(input("Enter the age"))
if (age>18):
    print("Eligible for vote")
elif(age<10):
    print("You are a kid")
else:
    print("not eligible")

Enter the age 8


You are a kid


In [3]:
#sum of number using loop
sum=0
for i in range(1,20):
    sum+=i
print(sum)

190


In [28]:
for i in range(8):
    print(i)

0
1
2
3
4
5
6
7


In [29]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


In [31]:
h=[1,2,'chsndn',12.3]
print(h[1])

2


In [32]:
h=[1,2,'chsndn',12.3]
h[2]=5
print(h)

[1, 2, 5, 12.3]


In [7]:
# std={
#     "Name": "Chadan","Anil"
#     "Id": 20122,20122}
# print(std)
# type(std)

In [ ]:
# type of files
# text file   -- csv_file
# binary file    --images,video
# .bin file     --
# files is lies in directoryies
# os model is used to work with directories
# directory is a container where we can store the files

In [45]:
# import os
# os.pathexists()     --for check the directories exist
# these two way to handle the directories

In [58]:
import os
os.getcwd()

'C:\\Users\\asus\\Documents\\data-analytics-learning-journey\\Day01_IBM'

In [47]:
# for change the directories
# os.chdir()      --for change the directories
# os.listdir()    --for list the directories
# os.mkdir()     --for make 
# os.rmdir()    --for remove

['.ipynb_checkpoints', 'IBM.ipynb']

In [48]:
# two type of path
# related path      -- file.txt
# appslute path   --c:/user/downloads/

In [50]:
# file
# open("filename","mode")
# used r for read files
# used w =for write any files
# used a for append 
# used x for create file
# used rt for read and write
# used b for binary file
# for read multiples lines use file.readlines

In [61]:
file= open("example.txt","w")
file.write("this is file handling")
file.close()
# content=file.readlines
# line=file.readline
# line=file.readlines
# print(content)


In [70]:
# os.path.exists()

In [62]:
file=open("example.txt","r")
content=file.readlines
line=file.readline
line=file.readlines
print(content)

<built-in method readlines of _io.TextIOWrapper object at 0x000001906B3F51C0>


In [64]:
file=open("example.txt","a")
file.write("This line is append")
file.close()

In [65]:
content=file.readlines
line=file.readline
line=file.readlines
print(content)

<built-in method readlines of _io.TextIOWrapper object at 0x000001906B3F4AC0>


In [66]:
with open("example.txt","r") as file:
    data=file.read
    print(data)

<built-in method read of _io.TextIOWrapper object at 0x000001906B3F4C80>


In [69]:
os.remove("example.txt")
print("file deleted")

file deleted


In [ ]:
# Input= Data given to the program.
# Output= Result produce by program.

# Input-->Processing-->Output-->Program.

In [12]:
name=input("Enter your name")
print("My name is: ",name)

Enter your name Chandan


My name is:  Chandan


In [16]:
age=int(input("Enter your age"))
print(age+5)

Enter your age 43


48


In [18]:
name="python"
version="3.13.7"
print(name,version)

python 3.13.7


In [22]:
name="python"
version="3.13.7"
print("Name:{},version:{}".format(name,version))

Name:python,version:3.13.7


In [26]:
# Take two input at a same time ,using space for differ the values. like 5 6 =11.
a,b=map(int,input("Enter two numbers:").split())  
print(a+b)

Enter two numbers: 5 5


10


In [28]:
print("Hello","World",sep="-",end="!")

Hello-World!

In [29]:
# import can be done by three ways:
# 1. import math:
#     math.sqrt(25)
# 2. import specific function:
#    from math import sqrt,pow 
#     sqrt(25)
# 3. import using alias np
#    import numpy as np

In [31]:
marks=int(input("Enter your marks"))
if (marks>=90):
    print("Grade A")
elif (marks>=80 and marks<90):
    print("Grade B")
elif (marks>=70 and marks<80):
    print("Grade C")
elif(marks>=50 and marks<70):
    print("Grade D")
else:
    print("Do Better")

Enter your marks 89


Grade B


In [1]:
# Day 02

In [3]:
# Copy: In copy we create a new object instead of shearing memory.
a=[1,2,3]
b=a
b.append(5)
print(b)
print(a)

[1, 2, 3, 5]
[1, 2, 3, 5]


In [9]:
original=[[1,2],3]
copy_list=original.copy()
copy_list[1]="CHANGED"
copy_list[0][1]=55
copy_list.append("NEW")              # shelo copy
print(original)
print(copy_list)
print(f"Original:{original}")
print(f"Copy list:{copy_list}")

[[1, 55], 3]
[[1, 55], 'CHANGED', 'NEW']
Original:[[1, 55], 3]
Copy list:[[1, 55], 'CHANGED', 'NEW']


In [11]:
import copy
a=[[1,2],[2,4]]
b=copy.deepcopy(a)                  # Deep copy
b[0][0]=99
print(a)
print(b)

[[1, 2], [2, 4]]
[[99, 2], [2, 4]]


In [12]:
# copy has two types:
# 1. shelo :
# 2. Deep :

In [2]:
# Numpy : Numerical python  scientific computing.
import numpy as np  # alias: it 
print(np.__version__)

2.3.5


In [4]:
arr=np.array([1,2,3,4,4,5])           #create a numpy array
print(arr)

[1 2 3 4 4 5]


In [7]:
print(np.zeros(3))
print(np.ones(3))             #create array using numpy functions/ methods.
print(np.arange(1,6))

[0. 0. 0.]
[1. 1. 1.]
[1 2 3 4 5]


In [18]:
p=np.zeros(3)
print(p,type(p))
print(p.dtype)
a=np.arange(1,6,2)             #(Start,Stop,Step)
print(a,type(a))
print(a.dtype)

[0. 0. 0.] <class 'numpy.ndarray'>
float64
[1 3 5] <class 'numpy.ndarray'>
int64


In [16]:
arr=np.array([[1,2,3],[4,5,6]])
print(type(arr))
print(arr.ndim)        # for dimension
print(arr.shape)       # for elements
print(arr.size)        # for how many elements are store
print(arr.dtype)       # for nature of the element

<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [30]:
arr= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr.ndim)
print(arr)
print(arr.shape)

3
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(2, 3, 3)


In [32]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [37]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr_2d=arr.reshape(2,3)
print(arr_2d)
arr_3d=arr.reshape(1,2,3)
print(arr_3d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


In [48]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [44]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr_5d=arr.reshape(1,1,1,1,6)
print(arr_5d)
print(arr_5d.shape)
print(arr_5d.flatten())
print(arr_5d.shape)

[[[[[1 2 3 4 5 6]]]]]
(1, 1, 1, 1, 6)
[1 2 3 4 5 6]
(1, 1, 1, 1, 6)


In [43]:
arr=np.array([10,20,30,40,50,60])
arr1=arr[arr>20]             #filter is do be done by boolen indexing
print(arr1)

[30 40 50 60]


In [47]:
arr=np.array([10,20,30,40,50,60])
arr1=arr[arr>20] 
print(np.sum(arr))       # for sum
print(np.max(arr))       # for max
print(np.min(arr))       # for min
print(np.std(arr))       # for standard daviation
print(np.var(arr))       # for variance
print(np.log(arr)) 
print(np.sin(arr))

210
60
10
17.07825127659933
291.6666666666667
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301 4.09434456]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062]


In [5]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
d=np.vstack((a,b))
print(c)
print(d)
print(np.hstack((a,b)))


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [19]:
arr=np.array([10,20,50,60,30,40])
print(np.split(arr,3))
print(np.where(arr==30))
print(np.argsort(arr))
print([arr>15]and[arr<40])
print(arr+10)                    #Broadcasting

[array([10, 20]), array([50, 60]), array([30, 40])]
(array([4]),)
[0 1 4 5 2 3]
[array([ True,  True, False, False,  True, False])]
[20 30 60 70 40 50]


In [10]:
data=np.array([40,10,30,20])
print(np.argsort(data))

[1 3 2 0]


In [16]:
matrix=np.array([[10,20,10],[20,10,20]])
print(matrix+np.array([10,20,10]))

[[20 40 20]
 [30 30 30]]


In [24]:
import pandas as pd

In [45]:
one=pd.Series([10,20,30,40,50],index=["a","b","c","d","e"])
one.name="column name"
one.index.name="Marks"
print(one)

Marks
a    10
b    20
c    30
d    40
e    50
Name: column name, dtype: int64


In [30]:
k=pd.DataFrame(one)
k

0
0  10
1  20
2  30
3  40
4  50
5  60
6  70

In [58]:
Two={"Name":["Chandan","Akash"],"Age":[21,22],"id":[20123,30124]}
Two
d=pd.DataFrame(Two)

Name  Age     id
0  Chandan   21  20123
1    Akash   22  30124

In [50]:
d.loc[1,'Name']

'Akash'

In [49]:
d.shape

(2, 3)

In [53]:
df=pd.read_excel(r"C:\Users\asus\Desktop\Datasets\Raw data .xlsx")
df

Id      Name  Lastname  Salary Department  Mobile no.
0    1     Anshu    Rajput   90000      Sales  8595787610
1    2    Manish     Kumar   62000  Marketing  8595787611
2    3     Aadil      Khan   70000    Finance  8595787612
3    4   Chandan    Thakur   80000         IT  8595787613
4    5      Aman     Anand   20000      Sales  8595787614
5    6     Badal     Singh   65000  Marketing  8595787615
6    7      Anil     Yadav   55000    Finance  8595787616
7    8     Akash     Verma   75000         IT  8595787617
8    9      Yash  Kushwaha   25000      Sales  8595787618
9   10  Abhishek     Yadav   95000  Marketing  8595787619
10  11   Aaditya     Yadav   10000    Finance  8595787620
11  12     Daksh   Chauhan   66000         IT  8595787621
12  13     Ayush     Singh   30000      Sales  8595787622
13  14      Arun     Singh   89000  Marketing  8595787623
14  15    Ashish     Rawat   90000    Finance  8595787624
15  16    Shivam    Thakur   91000         IT  8595787625
16  17     Swati    Thakur   92000      Sales  8595787626
17  18    Vineet      Ojha   93000  Marketing  8595787627
18  19    Sourav    Mathur   94000    Finance  8595787628
19  20    Yogesh    Sharma   95000         IT  8595787629

In [60]:
df.iloc[3]   # for print the specific row.

Id                     4
Name             Chandan
Lastname          Thakur
Salary             80000
Department            IT
Mobile no.    8595787613
Name: 3, dtype: object

In [63]:
df.loc[0,["Name","Salary"]]

Name      Anshu
Salary    90000
Name: 0, dtype: object

In [74]:
df[(df["Salary"]>50000) & (df["Department"]=="IT")]

Id     Name Lastname  Salary Department  Mobile no.
3    4  Chandan   Thakur   80000         IT  8595787613
7    8    Akash    Verma   75000         IT  8595787617
11  12    Daksh  Chauhan   66000         IT  8595787621
15  16   Shivam   Thakur   91000         IT  8595787625
19  20   Yogesh   Sharma   95000         IT  8595787629